language: clojure

lein: 
   - lein1
   - lein2
script: lein2 test :all

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

matrix:
 exclude:
  - lein: lein2
 allow_failures:
  - lein: lein1

#build_image: shippable/minv2:beta

notifications:
  email: false
